In [100]:
import pandas as pd

In [101]:
df = pd.read_excel('HR.xlsx')

In [102]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,y,travel_rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,n,travel_frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,y,travel_rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,n,travel_frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,n,travel_rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,n,travel_frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,n,travel_rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,n,travel_rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,n,travel_frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,n,travel_rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1452 non-null   float64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1466 non-null   float64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1449 non-null   float64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1461 non-null   float64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1464 non-null   float64
 13  JobInvolvement            1467 non-null   float64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1460 non-null   float64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1466 non-null   float64
 29  TrainingTimesLastYear     1466 non-null   float64
 30  WorkLifeBalance           1460 non-null   float64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(10), int64(16), object(9)
memory usage: 402.1+ KB

In [104]:
df.isnull().sum()

Age                         18
Attrition                    0
BusinessTravel               0
DailyRate                    4
Department                   0
DistanceFromHome            21
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      9
Gender                       0
HourlyRate                   6
JobInvolvement               3
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
MonthlyRate                  0
NumCompaniesWorked          10
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            4
TrainingTimesLastYear        4
WorkLifeBalance             10
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager         0
dtype: int64

In [105]:
age_median = df['Age'].median()
df['Age'].fillna(age_median, inplace=True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\170699217.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(age_median, inplace=True)

In [106]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,y,travel_rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,n,travel_frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,y,travel_rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,n,travel_frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,n,travel_rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,n,travel_frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,n,travel_rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,n,travel_rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,n,travel_frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,n,travel_rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [107]:
distance_median = df['DistanceFromHome'].median()
df['DistanceFromHome'].fillna(distance_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\1769277806.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DistanceFromHome'].fillna(distance_median, inplace = True)

In [108]:
dailyrate_median = df['DailyRate'].median()
df['DailyRate'].fillna(dailyrate_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\920892651.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DailyRate'].fillna(dailyrate_median, inplace = True)

In [109]:
enstatisfaction = df['EnvironmentSatisfaction'].median()
df['EnvironmentSatisfaction'].fillna(enstatisfaction, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\2774799634.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['EnvironmentSatisfaction'].fillna(enstatisfaction, inplace = True)

In [110]:
hourlyrate_median = df['HourlyRate'].median()
df['HourlyRate'].fillna(hourlyrate_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\968671962.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['HourlyRate'].fillna(hourlyrate_median, inplace = True)

In [111]:
jobinvolvement_median = df['JobInvolvement'].median()
df['JobInvolvement'].fillna(jobinvolvement_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\659060130.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['JobInvolvement'].fillna(jobinvolvement_median, inplace = True)

In [112]:
ncworked_median = df['NumCompaniesWorked'].median()
df['NumCompaniesWorked'].fillna(ncworked_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\3071927244.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['NumCompaniesWorked'].fillna(ncworked_median, inplace = True)

In [113]:
totalwyears_median = df['TotalWorkingYears'].median()
df['TotalWorkingYears'].fillna(totalwyears_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\384524112.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalWorkingYears'].fillna(totalwyears_median, inplace = True)

In [114]:
trainingtlyear_median = df['TrainingTimesLastYear'].median()
df['TrainingTimesLastYear'].fillna(trainingtlyear_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\3341710429.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TrainingTimesLastYear'].fillna(trainingtlyear_median, inplace = True)

In [115]:
worklifebalance_median = df['WorkLifeBalance'].median()
df['WorkLifeBalance'].fillna(worklifebalance_median, inplace = True)

C:\Users\Memmedov\AppData\Local\Temp\ipykernel_14400\300758227.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['WorkLifeBalance'].fillna(worklifebalance_median, inplace = True)

In [116]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,y,travel_rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,n,travel_frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,y,travel_rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,n,travel_frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,n,travel_rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,n,travel_frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,n,travel_rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,n,travel_rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,n,travel_frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,n,travel_rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [117]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [118]:
df.columns=['Age', 'Attrition', 'Business Travel', 'Daily Rate', 'Department', 'Distance From Home', 'Education', 'Education Field', 
            'Employee Count',  'Employee Number', 'Environment Satisfaction', 'Gender', 'Hourly Rate', 'Job Involvement', 'Job Level',
            'Job Role', 'Job Satisfaction', 'Marital Status', 'Monthly İncome', 'Monthly Rate', 'Num Companies Worked', 'Over 18',
            'Over Time', 'Percent Salary Hike', 'Performance Rating', 'Relationship Satisfaction', 'Standard Hours', 'Stock Option Level',
            'Total Working Years', 'Training Times Last Year', 'Work Life Balance', 'Years At Company', 'Years In Current Role', 'Years Since Last Promotion',
            'Years With Current Manager']

In [119]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,y,travel_rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,n,travel_frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,y,travel_rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,n,travel_frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,n,travel_rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,n,travel_frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,n,travel_rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,n,travel_rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,n,travel_frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,n,travel_rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [120]:
df['Attrition'] = df['Attrition'].replace({
    'y' : 'Yes',
    'n' : 'No' })

In [121]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,travel_rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,travel_frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,travel_rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,travel_frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,travel_rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,travel_frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,travel_rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,travel_rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,travel_frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,travel_rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [122]:
df['Business Travel'].unique()

array(['travel_rarely', 'travel_frequently', 'nn-Travel'], dtype=object)

In [123]:
df['Business Travel'] = df['Business Travel'].replace({
    'travel_rarely' : 'Rarely', 'travel_frequently' : 'Frequently',
    'nn-Travel' : 'No Travel' })

In [124]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,Rarely,1102.0,sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,Frequently,279.0,research & development,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,Rarely,1373.0,research & development,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,Frequently,1392.0,research & development,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,Rarely,591.0,research & development,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,Frequently,884.0,research & development,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,Rarely,613.0,research & development,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,Rarely,155.0,research & development,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,Frequently,1023.0,sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,Rarely,628.0,research & development,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [125]:
df['Department'].unique()

array(['sales', 'research & development', 'Human Resources'], dtype=object)

In [126]:
df['Department'] = df['Department'].replace({
    'sales' : 'Sales', 'research & development' : 'R&D',
    'Human Resources' : 'HR'})

In [127]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,Rarely,1102.0,Sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,Frequently,279.0,R&D,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,Rarely,1373.0,R&D,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,Frequently,1392.0,R&D,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,Rarely,591.0,R&D,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,Frequently,884.0,R&D,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,Rarely,613.0,R&D,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,Rarely,155.0,R&D,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,Frequently,1023.0,Sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,Rarely,628.0,R&D,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [128]:
df['Gender'].unique()

array(['f', 'm'], dtype=object)

In [129]:
df['Gender'] = df['Gender'].replace({
    'f' : 'Female', 'm' : 'Male'})

In [130]:
df['Gender']

0       Female
1         Male
2         Male
3       Female
4         Male
         ...
1465      Male
1466      Male
1467      Male
1468      Male
1469      Male
Name: Gender, Length: 1470, dtype: object

In [131]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,Rarely,1102.0,Sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,Frequently,279.0,R&D,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,Rarely,1373.0,R&D,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,Frequently,1392.0,R&D,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,Rarely,591.0,R&D,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,Frequently,884.0,R&D,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,Rarely,613.0,R&D,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,Rarely,155.0,R&D,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,Frequently,1023.0,Sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,Rarely,628.0,R&D,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [132]:
df['Marital Status'].unique()

array(['sngl', 'mrrd', 'Divorced'], dtype=object)

In [133]:
df['Marital Status'] = df['Marital Status'].replace({
    'sngl' : 'Single', 'mrrd' : 'Married'})

In [134]:
df['Marital Status']

0        Single
1       Married
2        Single
3       Married
4       Married
         ...
1465    Married
1466    Married
1467    Married
1468    Married
1469    Married
Name: Marital Status, Length: 1470, dtype: object

In [135]:
df['Over 18'].unique()

array(['Y'], dtype=object)

In [136]:
df['Over 18'] = df['Over 18'].replace({
    'Y' : 'Yes'})

In [137]:
df['Over 18']

0       Yes
1       Yes
2       Yes
3       Yes
4       Yes
       ...
1465    Yes
1466    Yes
1467    Yes
1468    Yes
1469    Yes
Name: Over 18, Length: 1470, dtype: object

In [138]:
df['Over Time'].unique()

array(['y', 'n'], dtype=object)

In [139]:
df['Over Time'] = df['Over Time'].replace({
    'y' : 'Yes', 'n' : 'No'})

In [140]:
df['Over Time']

0       Yes
1        No
2       Yes
3       Yes
4        No
       ...
1465     No
1466     No
1467    Yes
1468     No
1469     No
Name: Over Time, Length: 1470, dtype: object

In [141]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,Rarely,1102.0,Sales,1.0,2,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,Frequently,279.0,R&D,8.0,1,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,Rarely,1373.0,R&D,2.0,2,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,Frequently,1392.0,R&D,3.0,4,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,Rarely,591.0,R&D,2.0,1,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,Frequently,884.0,R&D,23.0,2,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,Rarely,613.0,R&D,6.0,1,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,Rarely,155.0,R&D,4.0,3,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,Frequently,1023.0,Sales,2.0,3,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,Rarely,628.0,R&D,8.0,3,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [145]:
df['Education'].unique()

array([2, 1, 4, 3, 5])

In [146]:
df['Education'] = df['Education'].replace({
    1 : 'Below Collage', 2 : 'Collage', 3 : 'Bachelor',
     4 : 'Master', 5 : 'Doctor'})

In [147]:
df

,Age,Attrition,Business Travel,Daily Rate,Department,Distance From Home,Education,Education Field,Employee Count,Employee Number,...,Relationship Satisfaction,Standard Hours,Stock Option Level,Total Working Years,Training Times Last Year,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Current Manager
0,41.0,Yes,Rarely,1102.0,Sales,1.0,Collage,Life Sciences,1,1,...,1,80,0,8.0,0.0,1.0,6,4,0,5
1,49.0,No,Frequently,279.0,R&D,8.0,Below Collage,Life Sciences,1,2,...,4,80,1,10.0,3.0,3.0,10,7,1,7
2,37.0,Yes,Rarely,1373.0,R&D,2.0,Collage,Other,1,4,...,2,80,0,7.0,3.0,3.0,0,0,0,0
3,33.0,No,Frequently,1392.0,R&D,3.0,Master,Life Sciences,1,5,...,3,80,0,8.0,3.0,3.0,8,7,3,0
4,27.0,No,Rarely,591.0,R&D,2.0,Below Collage,Medical,1,7,...,4,80,1,6.0,3.0,3.0,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36.0,No,Frequently,884.0,R&D,23.0,Collage,Medical,1,2061,...,3,80,1,17.0,3.0,3.0,5,2,0,3
1466,39.0,No,Rarely,613.0,R&D,6.0,Below Collage,Medical,1,2062,...,1,80,1,9.0,5.0,3.0,7,7,1,7
1467,27.0,No,Rarely,155.0,R&D,4.0,Bachelor,Life Sciences,1,2064,...,2,80,1,6.0,0.0,3.0,6,2,0,3
1468,49.0,No,Frequently,1023.0,Sales,2.0,Bachelor,Medical,1,2065,...,4,80,0,17.0,3.0,2.0,9,6,0,8
1469,34.0,No,Rarely,628.0,R&D,8.0,Bachelor,Medical,1,2068,...,1,80,0,6.0,3.0,4.0,4,3,1,2

In [148]:
df.isnull().sum()

Age                           0
Attrition                     0
Business Travel               0
Daily Rate                    0
Department                    0
Distance From Home            0
Education                     0
Education Field               0
Employee Count                0
Employee Number               0
Environment Satisfaction      0
Gender                        0
Hourly Rate                   0
Job Involvement               0
Job Level                     0
Job Role                      0
Job Satisfaction              0
Marital Status                0
Monthly İncome                0
Monthly Rate                  0
Num Companies Worked          0
Over 18                       0
Over Time                     0
Percent Salary Hike           0
Performance Rating            0
Relationship Satisfaction     0
Standard Hours                0
Stock Option Level            0
Total Working Years           0
Training Times Last Year      0
Work Life Balance             0
Years At Company              0
Years In Current Role         0
Years Since Last Promotion    0
Years With Current Manager    0
dtype: int64

In [149]:
df.to_excel("HR_cleaned.xlsx", index = False)